title: VegMadrid - Guía vegana, vegetariana y vegfriendly de Madrid
email: your-email@domain.com
description: Vegan Madrid

baseurl: "/"
url: http://keralahost.in/vegmadrid
google_adsense: Your-adsense-code

markdown: kramdown

name: VegMadrid - Guía vegana, vegetariana y vegfriendly de Madrid

date: 2019-05-01 14:22:38 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/vegmadrid/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: vegmadrid
